<!-- External JavaScripts -->
<script src="{{ asset("assets/client/js/plugins/jquery.min.js") }}"></script>
<script src="{{ asset("assets/client/js/plugins/bootstrap.bundle.min.js") }}"></script>
<script src="{{ asset("assets/client/js/plugins/bootstrap-slider.min.js") }}"></script>
<!-- <script src="assets/client/js/plugins/jquery.waypoints.min.js"></script> -->
<!-- <script src="assets/client/js/plugins/sticky.min.js"></script> -->
<script src="{{ asset("assets/client/js/plugins/swiper.min.js") }}"></script>
<script src="{{ asset("assets/client/js/plugins/countdown.js") }}"></script>
<!-- Footer Scripts -->
<script src="{{ asset("assets/client/js/theme.js") }}"></script>